name: CI

on: [push]

jobs:
  rubocop:
    name: Run rubocop with reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          bundler-cache: true

      - name: Run rubocop with reviewdog
        uses: reviewdog/action-rubocop@v2
        with:
          level: warning
          fail_on_error: true
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rspec:gemfile
          reporter: github-pr-review
          use_bundler: true

  rspec:
    name: Run rspec
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          bundler-cache: true

      - name: Run Rspec
        run: bundle exec rspec
